export enum CompanyData {
  SoftwareName = 'BuildCad',
  CompanyName = 'BUILD TECH ENTERPRISE S.R.L.',
  UniqueRegistrationCode = 'RO 	36290908',
  MatriculationNumber = 'J40/9300/2016',
  CompanyAddress = 'Bld. Tineretului, nr. 53, Sector 4, Bucuresti, Romania',
  CompanyPhoneNumber = '+40.724.645.018',
  CompanyEmail = 'office@buildtechent.ro',
  CompanyWebsite = 'buildtechent.ro',
  CompanyOwner = 'Dinu Mihail Iulian',
  CompanyBankAccount = 'INGB 00000 mock account',
  LastUpdate = '14.06.2023',
  CurrentVersion = 'V.1.0.',
  ContactType = 'Servicii proiectare constructii',
  AddressLocality = 'Bucuresti',
  AddressRegion = 'Bucuresti-Ilfov',
  PostalCode = '040352',
  StreetAddress = 'Bld. Tineretului, nr.53, Sector 4',
  Facebook = 'https://www.facebook.com/profile.php?id=100069652148555',
  Instagram = 'https://www.instagram.com/numeCompanie/',
  LinkedIn = 'https://www.linkedin.com/company/numeCompanie/',
  WhatsAppMessage = 'Buna ziua! Doresc sa va adresez urmatoarea intrebare. ',
  WhatsAppPhoneNumber = '+40724645018',
  FoundingYear = '2016',
}

// export enum CompanyData {
//   CompanyName = 'CompanyName',
//   UniqueRegistrationCode = 'UniqueRegistrationCode',
//   MatriculationNumber = 'MatriculationNumber',
//   CompanyAddress = 'CompanyAddress',
//   CompanyPhoneNumber = 'CompanyPhoneNumber',
//   CompanyEmail = 'CompanyEmail',
//   CompanyWebsite = 'CompanyWebsite',
//   CompanyOwner = 'CompanyOwner',
//   CompanyBankAccount = 'CompanyBankAccount',
//   LastUpdate = '22.09.2023',
//   CurrentVersion = 'V.1.0.',
//   ContactType = "ContactType",
//   AddressLocality = "AddressLocality",
//   AddressRegion = "AddressRegion",
//   PostalCode = "PostalCode",
//   StreetAddress = "StreetAddress",
//   Facebook = "https://www.facebook.com/numeCompanie",
//   Instagram = "https://www.instagram.com/numeCompanie/",
//   LinkedIn = "https://www.linkedin.com/company/numeCompanie/"
// }
